# Generated by Django 5.2.3 on 2025-06-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc_dni', models.CharField(max_length=20, unique=True)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_origen', models.CharField(max_length=100)),
                ('lugar_destino', models.CharField(max_length=100)),
                ('detalle_carga', models.TextField()),
                ('forma_pago', models.CharField(max_length=50)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_destinatario', to='core.cliente')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_remitente', to='core.cliente')),
            ],
        ),
    ]
